### ISSUE TITLE
> path.resolve is not a function TypeError on version 16.1.1

### ISSUE THREAD

**Issue by firmanserdana** [motdotla/dotenv#743]
Hello @motdotla 

it was working fine on 16.0.3

updating to 16.1.1 getting me those TypeError

Usecase: Cypress Automated Test (looks like any version)

![image](https://github.com/motdotla/dotenv/assets/56091175/af1703b4-b6e9-4478-aee9-ea7344fca894)

**Comment by EliaBracciSumo** [comment]
+1

**Comment by motdotla** [comment]
@firmanserdana can you show some of your test code? Where are you loading dotenv in your test code, etc?

**Comment by motdotla** [comment]
@firmanserdana nevermind. I have a failing example set up here: https://github.com/dotenv-org/examples/tree/master/dotenv-cypress-typescript

Working through the issue now.

**Comment by motdotla** [comment]
This will be the fix: https://github.com/motdotla/dotenv/pull/745

I set these as `false` incorrectly. Instead front-end code should have the necessary polyfils included from browserify. Looks like cypress does. 

I'll be updating the README shortly and releasing the patch. Until then you can install with:

```
npm install motdotla/dotenv#86ef7b2c7c9e8258743db7fedb7a25d6d57c3d15 --save
```

**Comment by motdotla** [comment]
Released. Use `16.1.3` or greater.

Closing this. If you still have trouble let me know and I will reopen.
